# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6f0417e3a54d5db5d34c08e7f2beb079060ace39ed361d9d33ff0f396cabf8af79add45430301991182976ce0e3e4cfb0594933767462ca3053290f8559636cd

test:
  secret_key_base: 0c07dd2771f750e46c2aa7137dbafed5465618ad5f620c580f85fd28be7914a5bbfefe550bc0321634df618e3472b2fd4a24b3e52d989b3eb990d5e556571e46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
